name: docker image build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    environment:
      name: production

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub.
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy image to Docker Hub.
        run: ./deployer.sh
